[package]
name = "shellblocks"
version = "0.7.1"
authors = ["Philipp Joram <mail@phijor.me>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
dirs = "5.0"
lazycell = { version = "1.3.0", default-features = false }
nix = { version = "0.29.0", features = ["hostname", "user", "term"] }
