[package]
name = "shellblocks"
version = "0.6.0"
authors = ["Philipp Joram <mail@phijor.me>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
libc = "~0.2.0"
dirs = "4.0"
gethostname = "~0.2.0"
lazycell = { version = "1.3.0", default-features = false }
